### ISSUE TITLE
Don't early hint fallback assets

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#624]
### Description

See https://github.com/brillout/vite-plugin-ssr/issues/618.

**Comment by brillout** [comment]
The implementation (https://github.com/brillout/vite-plugin-ssr/commit/693ff006e5971ed310a3916304157586e255c896) is brittle as it simply picks the first one. The user has to define the fallback assets after the primary one, in the hope that Vite doesn't shuffle the order in its internal asset graph representation.

**Comment by brillout** [comment]
Fix released in `0.4.75`. I didn't test it but it should work. Let me know if it doesn't.

**Comment by brillout** [comment]
Indeed, let me have a closer look at it.

**Comment by brillout** [comment]
Alright, new fix released at `0.4.76` which I tried and works with your repro. Sorry for the back-and-forth.

**Comment by FlorianCassayre** [comment]
I think this issue is back. In my case I can see both `.woff2` and `.woff` fonts registered for preloading (while it would make sense to only preload `.woff2`). I'm pretty much running the latest version of Vike.

Page: https://florian.cassayre.me/ ([source code](https://github.com/FlorianCassayre/florian.cassayre.me))

Here is another website from the community, written with Vike suffering from the same problem: https://ark-unity.com/ (this time with `.woff` and `.ttf`)

**Comment by brillout** [comment]
@FlorianCassayre This was [only applied to early hints](https://github.com/vikejs/vike/blob/385293c9822f2688fa01667ad2d73b966937a422/vike/node/runtime/renderPage/getEarlyHints.ts#L12-L17). But, indeed, we [should also apply it to preload tags](https://github.com/vikejs/vike/blob/385293c9822f2688fa01667ad2d73b966937a422/vike/node/runtime/html/injectAssets/getHtmlTags.ts#L76). I'll implement it this week (or PR welcome in case that's something you'd be up to).
